// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Entity struct {
	ID   string `json:"id"`
	Type string `json:"type"`
	Name string `json:"name"`
}

type Query struct {
}

type Relationship struct {
	Source *Entity `json:"source"`
	Target *Entity `json:"target"`
	Type   string  `json:"type"`
}

type SearchResult struct {
	Nodes []*Entity       `json:"nodes"`
	Edges []*Relationship `json:"edges"`
}
