package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	model1 "github.com/vasugupta1/RSSFeed/backend/internal/graph/model"
)

// SearchGraph is the resolver for the searchGraph field.
func (r *queryResolver) SearchGraph(ctx context.Context, keyword string) (*model1.SearchResult, error) {
	panic(fmt.Errorf("not implemented: SearchGraph - searchGraph"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
